sudo: required
services:
  - docker

before_install:
  - docker build -t rahulraut/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahulraut/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-936732622526"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
